import { VerticalBox } from "std-widgets.slint";
import { Translations } from "translations.slint";

export component HeaderBar {
    in property <string> show_version;
    in-out property <float> global_scale;

    VerticalBox {
        spacing: 6px * root.global_scale;

        Text {
            text: Translations.title_header;
            font-size: 24px * root.global_scale * Translations.font_global_scale;
            color: white;
            horizontal-alignment: center;
        }

        Text {
            text: Translations.subtitle_prefix + show_version;
            font-size: 14px * root.global_scale * Translations.font_global_scale;
            color: white;
            horizontal-alignment: center;
        }
    }
}
