import { VerticalBox } from "std-widgets.slint";

export component HeaderBar {
    in property <string> show_version;
    in-out property <float> global_scale;

    VerticalBox {
        spacing: 6px * root.global_scale;

        Text {
            text: "Talk freely fast with LanChGo App";
            font-size: 24px * root.global_scale;
            color: white;
            horizontal-alignment: center;
        }

        Text {
            text: "Made to solve a problem! LanChGo App " + show_version;
            font-size: 14px * root.global_scale;
            color: white;
            horizontal-alignment: center;
        }
    }
}
