import { VerticalBox } from "std-widgets.slint";

export component HeaderBar {
    in property <string> show_version;
    callback info_clicked();

    VerticalBox {
        spacing: 6px;

        Text {
            text: "Talk freely fast with LanChGo App";
            font-size: 24px;
            color: white;
            horizontal-alignment: center;
        }

        Text {
            text: "Made to solve a problem!" + " LanChGo App " + show_version;
            font-size: 14px;
            color: white;
            horizontal-alignment: center;
        }
    }
}
